---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  creationTimestamp: null
  name: nginx-root
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
