# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations: {}
  labels:
    app: postsapp
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/managed-by: odo
    app.kubernetes.io/managed-by-version: v1.0.1
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: postsapp
    app.openshift.io/runtime-version: latest
  name: frontend-postsapp
  namespace: posts
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: frontend-postsapp
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      creationTimestamp: null
      labels:
        deploymentconfig: frontend-postsapp
    spec:
      containers:
        - args:
            - -main
            - /opt/odo/bin/supervisord -c /opt/odo/conf/supervisor.conf
          command:
            - /opt/odo/bin/go-init
          env:
            - name: DEBUG_PORT
              value: "5858"
            - name: ODO_S2I_SCRIPTS_URL
              value: /usr/libexec/s2i
            - name: ODO_S2I_SCRIPTS_PROTOCOL
              value: image://
            - name: ODO_S2I_SRC_BIN_PATH
              value: /tmp
            - name: ODO_S2I_DEPLOYMENT_DIR
              value: /opt/app-root/src
            - name: ODO_S2I_WORKING_DIR
              value: /opt/app-root/src
            - name: ODO_S2I_BUILDER_IMG
              value: rhoar-nodejs/nodejs-10
            - name: ODO_SRC_BACKUP_DIR
              value: /opt/app-root/src-backup
          envFrom:
            - secretRef:
                name: backend-postsapp-8080
          image: image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:60e12250db082834ceb9056d1d2f82cdee795edbd79a4b23cb1f0426915c5360
          imagePullPolicy: IfNotPresent
          name: frontend-postsapp
          ports:
            - containerPort: 8080
              name: 8080-tcp
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/odo/
              name: odo-supervisord-shared-data
            - mountPath: /opt/app-root
              name: frontend-postsapp-s2idata
              subPath: app-root
      dnsPolicy: ClusterFirst
      initContainers:
        - args:
            - '\nSRC=/opt/app-root\nDEST=/mnt/app-root\n\nif [ -f $DEST/.delete-volume ]; then\n    rm -rf $DEST\nfi\n if [ -d $DEST ]; then\n    if [ -f $DEST/.sync-volume ]; then\n        if ! [[ \"$JUPYTER_SYNC_VOLUME\" =~ ^(false|no|n|0)$ ]]; then\n            JUPYTER_SYNC_VOLUME=yes\n        fi\n    fi\n     if [[ \"$JUPYTER_SYNC_VOLUME\" =~ ^(true|yes|y|1)$ ]]; then\n        rsync -ar --ignore-existing $SRC/. $DEST\n    fi\n     exit\nfi\n if [ -d $DEST.setup-volume ]; then\n    rm -rf $DEST.setup-volume\nfi\n\nmkdir -p $DEST.setup-volume\ntar -C $SRC -cf - . | tar -C $DEST.setup-volume -xvf -\nmv $DEST.setup-volume $DEST\n\t\t\t'
          command:
            - sh
            - -c
          image: image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:60e12250db082834ceb9056d1d2f82cdee795edbd79a4b23cb1f0426915c5360
          imagePullPolicy: IfNotPresent
          name: copy-files-to-volume
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /mnt
              name: frontend-postsapp-s2idata
        - args:
            - -r
            - /opt/odo-init/.
            - /opt/odo/
          command:
            - /usr/bin/cp
          image: registry.access.redhat.com/openshiftdo/odo-init-image-rhel7:1.0.0
          imagePullPolicy: IfNotPresent
          name: copy-supervisord
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/odo/
              name: odo-supervisord-shared-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: odo-supervisord-shared-data
        - name: frontend-postsapp-s2idata
          persistentVolumeClaim:
            claimName: frontend-postsapp-s2idata
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - frontend-postsapp
          - copy-files-to-volume
        from:
          kind: ImageStreamTag
          name: nodejs:latest
          namespace: openshift
        lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:60e12250db082834ceb9056d1d2f82cdee795edbd79a4b23cb1f0426915c5360
      type: ImageChange
