name: Bump & Tag New Release
on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
        - name: Run Gosec Security Scanner
          uses: securego/gosec@master
          with:
            args: -no-fail -fmt=json -out=results.json -stdout -verbose=text ./...
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          use_github_release_notes: true

