name: Github Actions - Shifter
on:
  pull_request:
    paths:
      - '**.go'
permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    working-directory: ./shifter

jobs:
  shifter-ci-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - uses: actions/checkout@v3
    - name: Run Golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
          version: v1.50.0
          args: --issues-exit-code=0 -vc ./.golangci.yaml ./...
          working-directory: /home/runner/work/shifter/shifter/shifter
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: -no-fail -fmt=sarif -out results.sarif -verbose=text ./...      
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif    
    - name: Run Build
      run:  make build   
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'gcr.io/shifter-lz-002/shifter:${{ github.sha }}'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'


#     ## we can update once we have unit testcases inplace
#     - name: Test
#       run: go test
