name: Github Actions - NPM

on:
  workflow_dispatch:
  pull_request:
     paths:
      - '**.js'
      - '**.vue'

defaults:
  run:
    working-directory: ./shifter-ui

jobs:
  npm-ci-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: '. --ext .vue,.js,.jsx,.cjs,.mjs --ignore-path .gitignore'
          workdir: './shifter-ui/'
      - name: Install
        run: npm install
      - name: Compile
        run: npm run build

      

      
