name: Security-Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Security Scan
      run: |
        cd shifter
        curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.12.0
        ./bin/gosec -no-fail -fmt=sarif -out=results.sarif -stdout -verbose=text ./...
    - name: Upload results.sarif file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: shifter/results.sarif
